### ISSUE TITLE
feat: Implement a draw question format

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#201]
As a user, I want a question where I'm asked to draw a specific kana or kanji

## Requirements

Implement a `DrawQuestion` model extending `Question`. The following instructions are supported:
-`custom`

⚠️ Schema incomplete

<details><summary><code>DrawQuestion</code> schema</summary>

⚠️ OpenAPI spec is used for simplicity only

```yaml
DrawQuestion:
 allOf:
   - refs: "#/components/schemas/Question"
   - type: object
     property:
       instructionOverride:
         type: string
         description: Instruction to display.
         example: Write the hiragana for "ka"
       hideSubject:
         type: boolean
         default: false
         description: | 
           Indique if the subject needs to be hidden. This can happen if the instruction override contains all the necessary information
       paths:
         type: array
         # Items to determine 
     required:
       - paths
```

</details> 

Possible instruction overrides are:
- _Write_ (default)
- _Write the <hiragana | katakana | kanji> for "<translation | pronunciation>"_

Implement a view that respects the following design.

## Design

<details>
    <summary>What the screenshot/video is presenting</summary> 
    
</details>

## Dependencies

Child of #160 

Depends on:

- #169
- #171 

Parent of:

- #
